### PR TITLE
Gst-base: fix version for gst_flow_combiner_ref/unref

### PR DESCRIPTION
**Pull request by fengalin**
gst_flow_combiner_ref/unref were introduced in gstreamer-1.12.1 but they inherit the `since version` declared for `GstFlowCombiner` which is 1.4.

See also: https://bugzilla.gnome.org/show_bug.cgi?id=788778

### CODE REVIEW

**Comment by sdroege** [comment]
Please squash both commits together. This also requires changes in gstreamer-rs though. Instead of requiring 1.12.1 for usage of gst_base::FlowCombiner, I'd like to use `g_boxed_copy` and `g_boxed_free` instead though. See `gst::ParseContext` for an example of that.

Do you want to provide a PR for that too?

**Comment by fengalin** [comment]
Yes, I will. I was just wondering how to handle this as Gir wouldn't use the version while generating `gst_base::FlowCombiner`. I'll take a look at `gst::ParseContext`.

**Comment by sdroege** [comment]
It unfortunately means that the whole type has to be done manually. Thanks! :)

**Review by sdroege — APPROVED** [review]
Thanks, looks good to me

**Pull request closed without merging**
