### PR TITLE
Bump to {glib,gobject}-sys 0.4.0

### PR DESCRIPTION
**Pull request by philn**
The 0.3.4 version is no longer available in Github.

### CODE REVIEW

**Comment by sdroege** [comment]
My idea would be to follow master, and have release branches that follow a release. That makes testing easier.

**Comment by philn** [comment]
Alright then, I will update the patch!

**Comment by philn** [comment]
This could then be merged into a release branch as-is, I suppose?

**Comment by sdroege** [comment]
Yes, this would be for the release branch and for master we just remove the version and only keep the git repository location.

**Pull request closed without merging**
